version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v1.6.1
    ports:
      - 6333:6333
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${LISTNING_PORT:-9092}:80
